server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 60000
  datasource:
    url: jdbc:postgresql://localhost:5432/airline
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect